apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tienda-demo
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: tienda-demo.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: tienda-demo
            port:
              number: 80
