apiVersion: v1
kind: Service
metadata:
  name: tienda-demo
  labels:
    app: tienda-demo
spec:
  type: NodePort
  selector:
    app: tienda-demo
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30080
    protocol: TCP
    name: http
