apiVersion: v1
kind: Service
metadata:
  name: tienda-demo
  labels:
    app: tienda-demo
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30081
      protocol: TCP
      name: http
  selector:
    app: tienda-demo
